Improved formatting to work on GitHub; minor corrections
jdsandifer/ALUnit pull request #2
Opened 2021-04-18 18:08 UTC by thelegendofbrian

2021-08-11 06:01 UTC, jdsandifer requested changes
Thanks a bunch for all of these edits! Sorry, it took me a while to review them.

There's just one change I'd like to see which I've commented on separately and then I'll be happy to merge this PR. Thanks again!

2021-08-11 06:01 UTC, jdsandifer commented on STYLE.md
>  The file header should have 3 parts: copyright line, filename and ALU
It's been a while since I wrote this, but based on the example, it's original lines 30 + 31 that need to be retained and original lines 29 + 32 - 35 that should be deleted.

Here's the complete paragraph that makes sense given the example that follows:

> The file header should have 4 parts: copyright line, filename and ALU 
> identifier line, paragragh(s) describing what's in the file, and paragragh(s) 
> identifying related files - with an empty line between each.

Can you make that change?

2021-08-14 18:33 UTC, thelegendofbrian commented on STYLE.md
>  The file header should have 3 parts: copyright line, filename and ALU
Should be good now!

2021-08-14 20:23 UTC, jdsandifer approved these changes
Looks good. Thanks!

2021-08-14 20:23 UTC, merged